export type BotEnv = Record<string, string | undefined>;

export type BotEnvConfig = {
	BOT_TOKEN?: string;
	TRACKER_TOKEN?: string;
	TRACKER_CLOUD_ORG_ID?: string;
	TRACKER_ORG_ID: string;
	WIKI_TOKEN?: string;
	WIKI_CLOUD_ORG_ID?: string;
	FIGMA_TOKEN?: string;
	JIRA_BASE_URL: string;
	JIRA_EMAIL: string;
	JIRA_API_TOKEN: string;
	JIRA_PROJECT_KEY: string;
	JIRA_BOARD_ID: number;
	POSTHOG_PERSONAL_API_KEY: string;
	POSTHOG_API_BASE_URL: string;
	OPENAI_API_KEY?: string;
	GEMINI_API_KEY?: string;
	OPENAI_MODEL: string;
	SOUL_PROMPT: string;
	ALLOWED_TG_IDS: string;
	CRON_STATUS_TIMEZONE: string;
	DEFAULT_TRACKER_QUEUE: string;
	DEFAULT_ISSUE_PREFIX: string;
	DEBUG_LOGS: boolean;
	TRACKER_API_BASE_URL: string;
	SUPERMEMORY_API_KEY: string;
	SUPERMEMORY_PROJECT_ID: string;
	SUPERMEMORY_TAG_PREFIX: string;
	HISTORY_MAX_MESSAGES: number;
	COMMENTS_CACHE_TTL_MS: number;
	COMMENTS_CACHE_MAX: number;
	COMMENTS_FETCH_CONCURRENCY: number;
	COMMENTS_FETCH_BUDGET_MS: number;
	TELEGRAM_TIMEOUT_SECONDS: number;
	TELEGRAM_TEXT_CHUNK_LIMIT: number;
	ALLOWED_TG_GROUPS: string;
	TELEGRAM_GROUP_REQUIRE_MENTION: boolean;
	IMAGE_MAX_BYTES: number;
	DOCUMENT_MAX_BYTES: number;
	ATTACHMENT_MAX_BYTES: number;
	WEB_SEARCH_ENABLED: boolean;
	WEB_SEARCH_CONTEXT_SIZE: string;
	TOOL_RATE_LIMITS: string;
	TOOL_APPROVAL_REQUIRED: string;
	TOOL_APPROVAL_TTL_MS: number;
	TOOL_APPROVAL_STORE_PATH: string;
	TOOL_ALLOWLIST_USER_IDS: string;
	TOOL_DENYLIST_USER_IDS: string;
	TOOL_ALLOWLIST_USER_TOOLS: string;
	TOOL_DENYLIST_USER_TOOLS: string;
	TOOL_ALLOWLIST_CHAT_TOOLS: string;
	TOOL_DENYLIST_CHAT_TOOLS: string;
	ORCHESTRATION_ALLOW_AGENTS: string;
	ORCHESTRATION_DENY_AGENTS: string;
	ORCHESTRATION_SUBAGENT_MAX_STEPS: number;
	ORCHESTRATION_SUBAGENT_MAX_TOOL_CALLS: number;
	ORCHESTRATION_SUBAGENT_TIMEOUT_MS: number;
	ORCHESTRATION_PARALLELISM: number;
	AGENT_DEFAULT_MAX_STEPS: number;
	AGENT_DEFAULT_TIMEOUT_MS: number;
	AGENT_CONFIG_OVERRIDES: string;
	SERVICE_NAME: string;
	RELEASE_VERSION?: string;
	COMMIT_HASH?: string;
	REGION?: string;
	INSTANCE_ID?: string;
};

export function loadBotEnv(env: BotEnv): BotEnvConfig {
	const BOT_TOKEN = env.BOT_TOKEN;
	const TRACKER_TOKEN = env.TRACKER_TOKEN;
	const TRACKER_CLOUD_ORG_ID = env.TRACKER_CLOUD_ORG_ID;
	const TRACKER_ORG_ID = env.TRACKER_ORG_ID ?? "";
	const WIKI_TOKEN = env.WIKI_TOKEN;
	const WIKI_CLOUD_ORG_ID = env.WIKI_CLOUD_ORG_ID;
	const FIGMA_TOKEN = env.FIGMA_TOKEN;
	const JIRA_BASE_URL = env.JIRA_BASE_URL ?? "";
	const JIRA_EMAIL = env.JIRA_EMAIL ?? "";
	const JIRA_API_TOKEN = env.JIRA_API_TOKEN ?? "";
	const JIRA_PROJECT_KEY = env.JIRA_PROJECT_KEY ?? "FL";
	const JIRA_BOARD_ID = Number.parseInt(env.JIRA_BOARD_ID ?? "", 10);
	const POSTHOG_PERSONAL_API_KEY = env.POSTHOG_PERSONAL_API_KEY ?? "";
	const POSTHOG_API_BASE_URL =
		env.POSTHOG_API_BASE_URL ?? "https://eu.posthog.com";
	const OPENAI_API_KEY = env.OPENAI_API_KEY;
	const GEMINI_API_KEY =
		env.GEMINI_API_KEY ??
		env.GOOGLE_GENERATIVE_AI_API_KEY ??
		env.GOOGLE_API_KEY;
	const OPENAI_MODEL = env.OPENAI_MODEL ?? "";
	const SOUL_PROMPT = env.SOUL_PROMPT ?? "";
	const ALLOWED_TG_IDS = env.ALLOWED_TG_IDS ?? "";
	const CRON_STATUS_TIMEZONE = env.CRON_STATUS_TIMEZONE ?? "UTC";
	const DEFAULT_TRACKER_QUEUE = env.DEFAULT_TRACKER_QUEUE ?? "PROJ";
	const DEFAULT_ISSUE_PREFIX =
		env.DEFAULT_ISSUE_PREFIX ?? DEFAULT_TRACKER_QUEUE;
	const DEBUG_LOGS = env.DEBUG_LOGS === "1";
	const TRACKER_API_BASE_URL =
		env.TRACKER_API_BASE_URL ?? "https://api.tracker.yandex.net";
	const SUPERMEMORY_API_KEY = env.SUPERMEMORY_API_KEY ?? "";
	const SUPERMEMORY_PROJECT_ID = env.SUPERMEMORY_PROJECT_ID ?? "";
	const SUPERMEMORY_TAG_PREFIX = env.SUPERMEMORY_TAG_PREFIX ?? "telegram:user:";
	const HISTORY_MAX_MESSAGES = Number.parseInt(
		env.HISTORY_MAX_MESSAGES ?? "20",
		10,
	);
	const COMMENTS_CACHE_TTL_MS = Number.parseInt(
		env.COMMENTS_CACHE_TTL_MS ?? "300000",
		10,
	);
	const COMMENTS_CACHE_MAX = Number.parseInt(
		env.COMMENTS_CACHE_MAX ?? "500",
		10,
	);
	const COMMENTS_FETCH_CONCURRENCY = Number.parseInt(
		env.COMMENTS_FETCH_CONCURRENCY ?? "4",
		10,
	);
	const COMMENTS_FETCH_BUDGET_MS = Number.parseInt(
		env.COMMENTS_FETCH_BUDGET_MS ?? "2500",
		10,
	);
	const TELEGRAM_TIMEOUT_SECONDS = Number.parseInt(
		env.TELEGRAM_TIMEOUT_SECONDS ?? "60",
		10,
	);
	const TELEGRAM_TEXT_CHUNK_LIMIT = Number.parseInt(
		env.TELEGRAM_TEXT_CHUNK_LIMIT ?? "4000",
		10,
	);
	const ALLOWED_TG_GROUPS = env.ALLOWED_TG_GROUPS ?? "";
	const TELEGRAM_GROUP_REQUIRE_MENTION =
		env.TELEGRAM_GROUP_REQUIRE_MENTION !== "0";
	const IMAGE_MAX_BYTES = Number.parseInt(env.IMAGE_MAX_BYTES ?? "5000000", 10);
	const DOCUMENT_MAX_BYTES = Number.parseInt(
		env.DOCUMENT_MAX_BYTES ?? "10000000",
		10,
	);
	const ATTACHMENT_MAX_BYTES = Number.parseInt(
		env.ATTACHMENT_MAX_BYTES ?? "8000000",
		10,
	);
	const WEB_SEARCH_ENABLED = env.WEB_SEARCH_ENABLED === "1";
	const WEB_SEARCH_CONTEXT_SIZE = env.WEB_SEARCH_CONTEXT_SIZE ?? "low";
	const TOOL_RATE_LIMITS = env.TOOL_RATE_LIMITS ?? "";
	const TOOL_APPROVAL_REQUIRED = env.TOOL_APPROVAL_REQUIRED ?? "";
	const TOOL_APPROVAL_TTL_MS = Number.parseInt(
		env.TOOL_APPROVAL_TTL_MS ?? "600000",
		10,
	);
	const TOOL_APPROVAL_STORE_PATH =
		env.TOOL_APPROVAL_STORE_PATH ?? "data/approvals/approvals.json";
	const TOOL_ALLOWLIST_USER_IDS = env.TOOL_ALLOWLIST_USER_IDS ?? "";
	const TOOL_DENYLIST_USER_IDS = env.TOOL_DENYLIST_USER_IDS ?? "";
	const TOOL_ALLOWLIST_USER_TOOLS = env.TOOL_ALLOWLIST_USER_TOOLS ?? "";
	const TOOL_DENYLIST_USER_TOOLS = env.TOOL_DENYLIST_USER_TOOLS ?? "";
	const TOOL_ALLOWLIST_CHAT_TOOLS = env.TOOL_ALLOWLIST_CHAT_TOOLS ?? "";
	const TOOL_DENYLIST_CHAT_TOOLS = env.TOOL_DENYLIST_CHAT_TOOLS ?? "";
	const ORCHESTRATION_ALLOW_AGENTS = env.ORCHESTRATION_ALLOW_AGENTS ?? "";
	const ORCHESTRATION_DENY_AGENTS = env.ORCHESTRATION_DENY_AGENTS ?? "";
	const ORCHESTRATION_SUBAGENT_MAX_STEPS = Number.parseInt(
		env.ORCHESTRATION_SUBAGENT_MAX_STEPS ?? "3",
		10,
	);
	const ORCHESTRATION_SUBAGENT_MAX_TOOL_CALLS = Number.parseInt(
		env.ORCHESTRATION_SUBAGENT_MAX_TOOL_CALLS ?? "4",
		10,
	);
	const ORCHESTRATION_SUBAGENT_TIMEOUT_MS = Number.parseInt(
		env.ORCHESTRATION_SUBAGENT_TIMEOUT_MS ?? "20000",
		10,
	);
	const ORCHESTRATION_PARALLELISM = Number.parseInt(
		env.ORCHESTRATION_PARALLELISM ?? "2",
		10,
	);
	const AGENT_DEFAULT_MAX_STEPS = Number.parseInt(
		env.AGENT_DEFAULT_MAX_STEPS ?? "6",
		10,
	);
	const AGENT_DEFAULT_TIMEOUT_MS = Number.parseInt(
		env.AGENT_DEFAULT_TIMEOUT_MS ?? "20000",
		10,
	);
	const AGENT_CONFIG_OVERRIDES = env.AGENT_CONFIG_OVERRIDES ?? "";
	const SERVICE_NAME = env.SERVICE_NAME ?? "omni";
	const RELEASE_VERSION = env.RELEASE_VERSION ?? env.APP_VERSION ?? undefined;
	const COMMIT_HASH = env.COMMIT_HASH ?? env.GIT_COMMIT ?? undefined;
	const REGION = env.REGION ?? undefined;
	const INSTANCE_ID = env.INSTANCE_ID ?? undefined;

	return {
		BOT_TOKEN,
		TRACKER_TOKEN,
		TRACKER_CLOUD_ORG_ID,
		TRACKER_ORG_ID,
		WIKI_TOKEN,
		WIKI_CLOUD_ORG_ID,
		FIGMA_TOKEN,
		JIRA_BASE_URL,
		JIRA_EMAIL,
		JIRA_API_TOKEN,
		JIRA_PROJECT_KEY,
		JIRA_BOARD_ID,
		POSTHOG_PERSONAL_API_KEY,
		POSTHOG_API_BASE_URL,
		OPENAI_API_KEY,
		GEMINI_API_KEY,
		OPENAI_MODEL,
		SOUL_PROMPT,
		ALLOWED_TG_IDS,
		CRON_STATUS_TIMEZONE,
		DEFAULT_TRACKER_QUEUE,
		DEFAULT_ISSUE_PREFIX,
		DEBUG_LOGS,
		TRACKER_API_BASE_URL,
		SUPERMEMORY_API_KEY,
		SUPERMEMORY_PROJECT_ID,
		SUPERMEMORY_TAG_PREFIX,
		HISTORY_MAX_MESSAGES,
		COMMENTS_CACHE_TTL_MS,
		COMMENTS_CACHE_MAX,
		COMMENTS_FETCH_CONCURRENCY,
		COMMENTS_FETCH_BUDGET_MS,
		TELEGRAM_TIMEOUT_SECONDS,
		TELEGRAM_TEXT_CHUNK_LIMIT,
		ALLOWED_TG_GROUPS,
		TELEGRAM_GROUP_REQUIRE_MENTION,
		IMAGE_MAX_BYTES,
		DOCUMENT_MAX_BYTES,
		ATTACHMENT_MAX_BYTES,
		WEB_SEARCH_ENABLED,
		WEB_SEARCH_CONTEXT_SIZE,
		TOOL_RATE_LIMITS,
		TOOL_APPROVAL_REQUIRED,
		TOOL_APPROVAL_TTL_MS,
		TOOL_APPROVAL_STORE_PATH,
		TOOL_ALLOWLIST_USER_IDS,
		TOOL_DENYLIST_USER_IDS,
		TOOL_ALLOWLIST_USER_TOOLS,
		TOOL_DENYLIST_USER_TOOLS,
		TOOL_ALLOWLIST_CHAT_TOOLS,
		TOOL_DENYLIST_CHAT_TOOLS,
		ORCHESTRATION_ALLOW_AGENTS,
		ORCHESTRATION_DENY_AGENTS,
		ORCHESTRATION_SUBAGENT_MAX_STEPS,
		ORCHESTRATION_SUBAGENT_MAX_TOOL_CALLS,
		ORCHESTRATION_SUBAGENT_TIMEOUT_MS,
		ORCHESTRATION_PARALLELISM,
		AGENT_DEFAULT_MAX_STEPS,
		AGENT_DEFAULT_TIMEOUT_MS,
		AGENT_CONFIG_OVERRIDES,
		SERVICE_NAME,
		RELEASE_VERSION,
		COMMIT_HASH,
		REGION,
		INSTANCE_ID,
	};
}
